version: "3"

services:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Docker/Dockerfile
    depends_on:
      - mongo

  frontend:
    restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
